using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Diagnostics;

namespace VoodooBuild
{
    class Program
    {
        static void Main(string[] args)
        {
            String buildFile = args[0].Trim();

            Int32 versionMajor = Convert.ToInt32(args[1]);
            Int32 versionMinor = Convert.ToInt32(args[2]);
            Int32 versionPatch = Convert.ToInt32(args[3]);
            bool ignoreTime = args.Length > 4 ? Convert.ToBoolean(args[4]) : false;

            Int32 buildCount = 0;

            String[] lines = null;
            DateTime lastRun = new DateTime(0);

            try
            {
                if (File.Exists(buildFile))
                {
                    lines = File.ReadAllLines(buildFile);
                    if (lines.Length > 7)
                    {
                        String lastTime = lines[1].Substring(3);
                        lastRun = Convert.ToDateTime(lastTime);

                        Regex buildCountExpr = new Regex(@"\#define VOODOO_PROJECT_VERSION_BUILD (?<count>[0-9]+)");
                        String buildLine = buildCountExpr.Match(lines[5]).Groups["count"].Value;
                        buildCount = Convert.ToInt32(buildLine);
                    }
                }
            }
            catch (Exception ex) 
            {
                Console.WriteLine("VoodooBuild: Error reading file: " + ex.Message);
            }

            DateTime buildtime = DateTime.UtcNow;

            if (ignoreTime || ((DateTime.Now - lastRun).TotalHours > 1))
            {
                ++buildCount;

                Process p = new Process();
                p.StartInfo.UseShellExecute = false;
                p.StartInfo.RedirectStandardOutput = true;
                p.StartInfo.FileName = "cmd";
                p.StartInfo.Arguments = "/c git describe";
                p.Start();
                String gitDesc = p.StandardOutput.ReadToEnd().TrimEnd('\n');
                p.WaitForExit();

                Console.WriteLine("Time since last counted build: {0}", DateTime.Now - lastRun);
                Console.WriteLine("Build number: {0}", buildCount);
                Console.WriteLine("Git ID: {0}", gitDesc);

                lines = new String[7];
                lines[0] = "// This file is automatically generated by the VoodooBuild tool, to track git revision and build count. Any changes will be lost.";
                lines[1] = String.Format("// {0}", buildtime);
                lines[2] = String.Format("#define VOODOO_PROJECT_VERSION_ID VSTR(\"{0}\")", gitDesc);
                lines[3] = String.Format("#define VOODOO_PROJECT_VERSION_MAJOR {0}", versionMajor);
                lines[4] = String.Format("#define VOODOO_PROJECT_VERSION_MINOR {0}", versionMinor);
                lines[5] = String.Format("#define VOODOO_PROJECT_VERSION_PATCH {0}", versionPatch);
                lines[6] = String.Format("#define VOODOO_PROJECT_VERSION_BUILD {0}", buildCount);
                File.WriteAllLines(buildFile, lines);

                Console.WriteLine("VoodooBuild: Updated version header.");
            }
            else
            {
                Console.WriteLine("VoodooBuild: No header update needed.");
            }
        }
    }
}
