// DX89.idl : IDL source for DX89
//

// This file will be processed by the MIDL tool to
// produce the type library (DX89.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
cpp_quote("#include \"VoodooFramework.hpp\"")

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,	
	pointer_default(unique)
]
interface IComponentRegistrar : IDispatch
{
	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
	[id(2)]	HRESULT RegisterAll();
	[id(3)]	HRESULT UnregisterAll();
	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
};

[
	uuid(4A2FCC0A-83CC-4E5F-A56F-DAFD93ACAE82),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a,"{A88C4E5C-714D-417E-A61D-CC629ED95130}")
]
library DX89Lib
{
	importlib("stdole2.tlb");
    importlib("Voodoo_Core.tlb");

	[
		uuid(A88C4E5C-714D-417E-A61D-CC629ED95130)		
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};

	[		
		uuid(B09FABF5-D8D4-4AA3-8A21-080F0693C0E3)		
	]
	coclass GenericDX89
	{
		[default] interface IVoodooAdapter;
	};
};

